title = "free5gc"

[app]
# error, debug, warn, info, trace
logLevel = "debug"
logFolder = "./logs"

[controller]
n2Interface = "ens3"
n2IpFrom = "223.193.7.230"
n2IpTo = "223.193.7.239"
n3Interface = "ens3"
n3IpFrom = "1.1.1.1"
n3IpTo = "1.1.1.1"
dnInterface = "ens3"
dnIp = "1.1.1.3"
ueNum = 1
uePerGnb = 88888
uePerSec = 10
initPDUWhenAllUERegistered = false
emulateUserPlane = true
userPlaneEmulateUEMaxNum = 100

[reporter]
outputFolder = "./output"
recordGranularity = "100ms" # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
exportRawData = true

[gnb]
name = "test-gnb"
mcc = "208"
mnc = "93"
tac = 1
idLength = 32
sst = 0x01
sd = 0x010203

[ue]
# only support imsi now
supiType = "imsi"
supiFrom = "imsi-208930000000200"
supiTo = "imsi-208930000010100"
mcc = "208"
mnc = "93"
key = "8baf473f2f8fd09487cccbd7097c6862"
op = "8e27b6af0e692e750f32667a3b14605d"
opType = "OPC"
amf = "8000"

[ue.dataRate]
uplink = "full"
downlink = "full"

[ue.sessions]
[ue.sessions.0]
# IPv4, IPv6, IPv4AndIPv6
type = "IPv4"
apn = "internet"
sst = 0x01
sd = 0x010203


[amf]
ip = "223.193.7.254"
port = 38412

[upf]
ip = "1.1.1.2"
port = 2152
