title = "Example Config"

[app]
# error, debug, warn, info, trace
logLevel = "debug"
# logPath = ""

[controller]
n2IpFrom = "223.193.7.253"
n2IpTo = "223.193.7.253"
n3Ip = "1.1.1.1"
ueNum = 1
uePerGnb = 20000
uePerSec = 3
initPDUWhenAllUERegistered = false

[gnb]
name = "test-gnb"
mcc = "208"
mnc = "93"
tac = 1
idLength = 32
sst = 0x01
sd = 0x010203

[ue]
# only support imsi now
supiType = "imsi"
supiFrom = "imsi-208930000000100"
supiTo = "imsi-208930000010100"
mcc = "208"
mnc = "93"
key = "8baf473f2f8fd09487cccbd7097c6862"
op = "8e27b6af0e692e750f32667a3b14605d"
opType = "OPC"
amf = "8000"

    [ue.dataRate]
    uplink = "full"
    downlink = "full"

    [ue.sessions]
        [ue.sessions.0]
        # IPv4, IPv6, IPv4AndIPv6
        type = "IPv4"
        apn = "internet"
        sst = 0x01
        sd = 0x010203


[amf]
ip = "223.193.7.254"
# ip = "127.0.0.1"
port = 38412
